# Generated by Django 3.1.6 on 2021-02-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Book Name')),
                ('author', models.CharField(max_length=70, verbose_name='Author')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
    ]
